const fs=require('fs');
const d=String.fromCharCode(60),s=String.fromCharCode(62),amp=String.fromCharCode(38);
const L=[];const a=t=>L.push(t);

a('"use client";');
a('import React,{useState}from"react";');
a('');
a('const STORIES=[');
a('  {id:1,name:"Hikayem",avatar:"🇹🇷",isOwn:true,seen:false,color:["#e63946","#c1121f"]},');
a('  {id:2,name:"Ahmet K.",avatar:"AK",isOwn:false,seen:false,color:["#1d3557","#457b9d"]},');
a('  {id:3,name:"Zeynep M.",avatar:"ZM",isOwn:false,seen:false,color:["#e63946","#457b9d"]},');
a('  {id:4,name:"Burak T.",avatar:"BT",isOwn:false,seen:true,color:["#2d6a4f","#40916c"]},');
a('  {id:5,name:"Selin Ö.",avatar:"SÖ",isOwn:false,seen:false,color:["#e76f51","#f4a261"]},');
a('  {id:6,name:"Emre Y.",avatar:"EY",isOwn:false,seen:true,color:["#457b9d","#1d3557"]},');
a('  {id:7,name:"Ayşe D.",avatar:"AD",isOwn:false,seen:false,color:["#c1121f","#e63946"]},');
a('  {id:8,name:"Can B.",avatar:"CB",isOwn:false,seen:false,color:["#40916c","#2d6a4f"]},');
a('];');
a('');
a('export default function StoryBar(){');
a('  const [active,setActive]=useState'+d+'number|null'+s+'(null);');
a('  const st=active?STORIES.find(x=>x.id===active):null;');
a('  return(');
a('    '+d+'React.Fragment'+s);
a('      '+d+'div style={{background:"#fff",borderRadius:16,border:"1px solid #eef0f2",boxShadow:"0 1px 6px rgba(0,0,0,0.06)",padding:"14px 16px"}}'+s);
a('        '+d+'div style={{display:"flex",gap:14,overflowX:"auto",paddingBottom:2,scrollbarWidth:"none" as "none"}}'+s);
a('        {STORIES.map(story=>(');
a('          '+d+'button key={story.id} onClick={()=>setActive(story.id)} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6,flexShrink:0,background:"none",border:"none",cursor:"pointer",padding:0}}'+s);
a('            '+d+'div style={{padding:2,borderRadius:"50%",background:story.seen?"#d1d5db":`linear-gradient(135deg,${story.color[0]},${story.color[1]})`}}'+s);
a('              '+d+'div style={{width:52,height:52,borderRadius:"50%",border:"2px solid #fff",display:"flex",alignItems:"center",justifyContent:"center",overflow:"hidden",position:"relative",background:story.isOwn?"#E30A17":`linear-gradient(135deg,${story.color[0]},${story.color[1]})`}}'+s);
a('                {story.isOwn?(');
a('                  '+d+'svg width="52" height="52" viewBox="0 0 900 900" xmlns="http://www.w3.org/2000/svg" style={{display:"block"}}'+s);
a('                    '+d+'rect width="900" height="900" fill="#E30A17"/'+s);
a('                    '+d+'g transform="translate(0,150)"'+s);
a('                      '+d+'circle cx="300" cy="300" r="200" fill="white"/'+s);
a('                      '+d+'circle cx="360" cy="300" r="160" fill="#E30A17"/'+s);
a('                      '+d+'g transform="translate(530,300) rotate(-12)"'+s+d+'polygon fill="white" points="0,-80 18.6,-57.2 59.5,-24.7 30.4,21.9 37.3,65.2 0,40 -37.3,65.2 -30.4,21.9 -59.5,-24.7 -18.6,-57.2"/'+s+d+'/g'+s);
a('                    '+d+'/g'+s);
a('                  '+d+'/svg'+s);
a('                ):('+d+'span style={{color:"#fff",fontWeight:800,fontSize:12}}'+s+'{story.avatar}'+d+'/span'+s+')}');
a('                {story.isOwn'+amp+amp+'('+d+'div style={{position:"absolute",bottom:-1,right:-1,width:18,height:18,borderRadius:"50%",background:"#e63946",border:"2px solid #fff",display:"flex",alignItems:"center",justifyContent:"center"}}'+s+d+'svg width="8" height="8" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" viewBox="0 0 24 24"'+s+d+'path d="M12 5v14M5 12h14"/'+s+d+'/svg'+s+d+'/div'+s+')}');
a('              '+d+'/div'+s);
a('            '+d+'/div'+s);
a('            '+d+'span style={{fontSize:10.5,color:"#374151",fontWeight:500,maxWidth:58,textAlign:"center",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",display:"block"}}'+s+'{story.name}'+d+'/span'+s);
a('          '+d+'/button'+s);
a('        ))}');
a('        '+d+'/div'+s);
a('      '+d+'/div'+s);

fs.writeFileSync('c:/Users/agity/Desktop/akgencler.com.tr/fix_storybar_data.json',JSON.stringify(L),'utf8');
console.log('part1 ok',L.length);
