const fs=require('fs');
const d=String.fromCharCode(60),s=String.fromCharCode(62),amp=String.fromCharCode(38);
const L=[];const a=t=>L.push(t);

a('"use client";');
a('import Link from"next/link";');
a('import{usePathname}from"next/navigation";');
a('');
a('const NAV=[');
a('  {href:"/",label:"Ana Sayfa",badge:null,icon:"home"},');
a('  {href:"/kesfet",label:"Keşfet",badge:null,icon:"search"},');
a('  {href:"/topluluklar",label:"Topluluklar",badge:"12",icon:"users"},');
a('  {href:"/etkinlikler",label:"Etkinlikler",badge:"3",icon:"calendar"},');
a('  {href:"/mesajlar",label:"Mesajlar",badge:"3",icon:"message"},');
a('  {href:"/kaydet",label:"Kaydettiklerim",badge:null,icon:"bookmark"},');
a('  {href:"/profil",label:"Profilim",badge:null,icon:"user"},');
a('];');
a('');
a('const TRENDS=[');
a('  {tag:"#AkGençler",count:"12.4K"},');
a('  {tag:"#TürkiyeGençliği",count:"8.9K"},');
a('  {tag:"#GençFikirler",count:"6.2K"},');
a('  {tag:"#İnovasyon",count:"4.8K"},');
a('  {tag:"#Teknoloji",count:"3.1K"},');
a('];');
a('');
a('function HomeIcon(){return('+d+'svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"'+s+d+'path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/'+s+d+'polyline points="9 22 9 12 15 12 15 22"/'+s+d+'/svg'+s+');}');
a('function SearchIcon(){return('+d+'svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"'+s+d+'circle cx="11" cy="11" r="8"/'+s+d+'path d="m21 21-4.35-4.35"/'+s+d+'/svg'+s+');}');
a('function UsersIcon(){return('+d+'svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"'+s+d+'path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/'+s+d+'circle cx="9" cy="7" r="4"/'+s+d+'path d="M23 21v-2a4 4 0 0 0-3-3.87"/'+s+d+'path d="M16 3.13a4 4 0 0 1 0 7.75"/'+s+d+'/svg'+s+');}');
a('function CalIcon(){return('+d+'svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"'+s+d+'rect x="3" y="4" width="18" height="18" rx="2" ry="2"/'+s+d+'line x1="16" y1="2" x2="16" y2="6"/'+s+d+'line x1="8" y1="2" x2="8" y2="6"/'+s+d+'line x1="3" y1="10" x2="21" y2="10"/'+s+d+'/svg'+s+');}');
a('function MsgIcon(){return('+d+'svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"'+s+d+'path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/'+s+d+'/svg'+s+');}');
a('function BmIcon(){return('+d+'svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"'+s+d+'path d="m19 21-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/'+s+d+'/svg'+s+');}');
a('function UserIcon(){return('+d+'svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"'+s+d+'path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/'+s+d+'circle cx="12" cy="7" r="4"/'+s+d+'/svg'+s+');}');
a('const ICONS:Record'+d+'string,()=>JSX.Element'+s+'={home:HomeIcon,search:SearchIcon,users:UsersIcon,calendar:CalIcon,message:MsgIcon,bookmark:BmIcon,user:UserIcon};');
a('');

fs.writeFileSync('c:/Users/agity/Desktop/akgencler.com.tr/fix_sb_data.json',JSON.stringify(L),'utf8');
console.log('part1 done',L.length);
