const fs=require('fs');
const d=String.fromCharCode(60),s=String.fromCharCode(62),amp=String.fromCharCode(38);
const L=[];const a=t=>L.push(t);

a('"use client";');
a('import React,{useState}from"react";');
a('import PostCard from"./PostCard";');
a('const POSTS=[');
a('  {id:1,author:{name:"Ahmet Kaya",username:"ahmetkaya_tr",avatar:"AK",verified:true},content:"Türkiye\'de genç girişimciler için muazzam fırsatlar var. 🚀",image:null,likes:248,comments:34,shares:12,time:"2 saat önce",tags:["#girişim","#startup"],liked:false,bookmarked:false},');
a('  {id:2,author:{name:"Zeynep Mercan",username:"zeynepmercan",avatar:"ZM",verified:false},content:"TÜBİTAK\'tan destek aldığımı öğrendim! 🎉 İnanmaya devam edin.",image:"gradient1",likes:512,comments:89,shares:67,time:"4 saat önce",tags:["#tubitak","#bilim"],liked:true,bookmarked:false},');
a('  {id:3,author:{name:"Burak Tekin",username:"burak_tekin",avatar:"BT",verified:true},content:"İstanbul\'da gençlik zirvesine katıldım. 500+ genç lider bir aradaydı! 📝",image:null,likes:189,comments:21,shares:8,time:"6 saat önce",tags:["#liderlik","#zirve"],liked:false,bookmarked:true},');
a('  {id:4,author:{name:"Selin Öztürk",username:"selinozt",avatar:"SÖ",verified:false},content:"Geçen ay 3 kurs, 2 kitap, bir mentorluk programı. Kendinize yatırım yapın! 💪",image:"gradient2",likes:334,comments:56,shares:23,time:"8 saat önce",tags:["#eğitim"],liked:false,bookmarked:false},');
a('  {id:5,author:{name:"Emre Yıldız",username:"emreyildiz42",avatar:"EY",verified:true},content:"Yapay zeka dünyası inanılmaz hızla gelişiyor. Bu trendi yakalayalım! 🤖🇹🇷",image:"gradient3",likes:671,comments:112,shares:89,time:"12 saat önce",tags:["#yapayZeka","#teknoloji"],liked:true,bookmarked:false},');
a('];');
a('interface FeedProps{activeTab:"kesfet"|"akis"|"trend";}');
a('export default function Feed({activeTab}:FeedProps){');
a('  const [posts,setPosts]=useState(POSTS);');
a('  const [txt,setTxt]=useState("");');
a('  const [posting,setPosting]=useState(false);');
a('  const chars=txt.length,MAX=280;');
a('  const over=chars'+d+'MAX,near=chars'+d+'MAX*0.8;');
a('  const C=2*Math.PI*12,dash=C*(1-Math.min(chars/MAX,1));');
a('  function submit(){if(!txt.trim()||over)return;setPosting(true);setTimeout(()=>{setPosts(p=>[{id:Date.now(),author:{name:"Ak Genç",username:"akgenc_tr",avatar:"AG",verified:false},content:txt,image:null,likes:0,comments:0,shares:0,time:"Az önce",tags:[],liked:false,bookmarked:false},...p]);setTxt("");setPosting(false);},700);}');
a('  function like(id:number){setPosts(p=>p.map(x=>x.id===id?{...x,liked:!x.liked,likes:x.liked?x.likes-1:x.likes+1}:x));}');
a('  function bm(id:number){setPosts(p=>p.map(x=>x.id===id?{...x,bookmarked:!x.bookmarked}:x));}');
a('  const dp=activeTab==="trend"?[...posts].sort((a,b)=>b.likes-a.likes):posts;');
a('  return(');
a('    '+d+'div style={{display:"flex",flexDirection:"column",gap:14}}'+s);
a('      '+d+'div style={{background:"#fff",borderRadius:16,border:"1px solid #eef0f2",boxShadow:"0 1px 6px rgba(0,0,0,0.06)",overflow:"hidden"}}'+s);
a('        '+d+'div style={{display:"flex",alignItems:"flex-start",gap:12,padding:"16px 16px 10px"}}'+s);
a('          '+d+'div style={{width:40,height:40,borderRadius:"50%",background:"linear-gradient(135deg,#e63946,#1d3557)",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontWeight:800,fontSize:12,flexShrink:0,boxShadow:"0 2px 6px rgba(230,57,70,0.25)"}}'+s+'AG'+d+'/div'+s);
a('          '+d+'textarea value={txt} onChange={e=>setTxt(e.target.value)} placeholder="Ne düşünüyorsun? Fikirlerini paylaş..." rows={txt.length'+d+'0?3:2} style={{flex:1,resize:"none",fontSize:14,color:"#1c1e21",background:"transparent",border:"none",outline:"none",lineHeight:1.65,fontFamily:"inherit",paddingTop:6,width:"100%"}}'+s+d+'/textarea'+s);
a('        '+d+'/div'+s);
a('        '+d+'div style={{height:1,background:"#f3f4f6",margin:"0 16px"}}'+s+d+'/div'+s);
a('        '+d+'div style={{display:"flex",alignItems:"center",padding:"8px 12px",gap:2}}'+s);
a('          {[{e:"🖼️",l:"Fotoğraf"},{e:"🎬",l:"Video"},{e:"📊",l:"Anket"},{e:"😊",l:"Duygu"}].map((b,i)=>('+d+'button key={i} title={b.l} style={{padding:"6px 8px",border:"none",background:"none",cursor:"pointer",borderRadius:8,fontSize:15}}'+s+'{b.e}'+d+'/button'+s+'))}');
a('          '+d+'div style={{flex:1}}'+s+d+'/div'+s);
a('          {chars'+d+'0'+amp+amp+'('+d+'div style={{display:"flex",alignItems:"center",gap:6,marginRight:8}}'+s+'          '+d+'svg width="28" height="28" viewBox="0 0 28 28"'+s+d+'circle cx="14" cy="14" r="12" fill="none" stroke="#f0f0f0" strokeWidth="2.5"/'+s+d+'circle cx="14" cy="14" r="12" fill="none" stroke={over?"#e63946":near?"#f4a261":"#2a9d8f"} strokeWidth="2.5" strokeDasharray={C} strokeDashoffset={dash} strokeLinecap="round" style={{transform:"rotate(-90deg)",transformOrigin:"50% 50%",transition:"all 0.2s"}}'+'/'+s+d+'/svg'+s+'          '+d+'span style={{fontSize:11,fontWeight:600,color:over?"#e63946":near?"#f4a261":"#9ca3af",minWidth:22,textAlign:"right"}}'+s+'{over?"-"+(chars-MAX):(MAX-chars)}'+d+'/span'+s+d+'/div'+s+')}');
a('          '+d+'button onClick={submit} disabled={!txt.trim()||posting||over} style={{display:"flex",alignItems:"center",gap:6,background:"linear-gradient(135deg,#e63946,#c1121f)",color:"#fff",border:"none",borderRadius:20,padding:"9px 20px",fontSize:13,fontWeight:700,cursor:"pointer",opacity:!txt.trim()||over?0.45:1,whiteSpace:"nowrap"}}'+s+'{posting?"Paylaşılıyor...":"Paylaş"}'+d+'/button'+s);
a('        '+d+'/div'+s);
a('      '+d+'/div'+s);

fs.writeFileSync('c:/Users/agity/Desktop/akgencler.com.tr/fix_feed_data.json',JSON.stringify(L),'utf8');
console.log('feed part1 ok',L.length);
