const fs=require('fs');
const d=String.fromCharCode(60),s=String.fromCharCode(62),amp=String.fromCharCode(38);
const L=[];const a=t=>L.push(t);

a('"use client";');
a('import React,{useState}from"react";');
a('import PageLayout from"@/components/PageLayout";');
a('');
a('const POSTS=[');
a('  {id:1,content:"Türkiye\'de genç girişimciler için muazzam fırsatlar var! 🚀",likes:248,comments:34,shares:12,time:"2 saat önce",tags:["#girişim","#startup"],img:"linear-gradient(135deg,#e63946,#c1121f)"},');
a('  {id:2,content:"Yapay zeka ile hayatımız nasıl değişiyor? 🤖 Kapsamlı araştırma yaptım.",likes:189,comments:21,shares:8,time:"1 gün önce",tags:["#yapayZeka","#teknoloji"],img:"linear-gradient(135deg,#1d3557,#457b9d)"},');
a('  {id:3,content:"Gençlik zirvesinden notlar: Türkiye\'nin geleceği parlak! 🌟",likes:334,comments:56,shares:23,time:"3 gün önce",tags:["#liderlik","#gençlik"],img:"linear-gradient(135deg,#2d6a4f,#52b788)"},');
a('  {id:4,content:"Boğaziçi\'nde harika bir seminer vardı, çok şey öğrendim 📚",likes:156,comments:18,shares:6,time:"5 gün önce",tags:["#eğitim","#üniversite"],img:"linear-gradient(135deg,#e76f51,#f4a261)"},');
a('  {id:5,content:"Yeni proje ortağım buldum! Birlikte büyük işler yapacağız 🤝",likes:421,comments:67,shares:31,time:"1 hafta önce",tags:["#işbirliği"],img:"linear-gradient(135deg,#457b9d,#1d3557)"},');
a('  {id:6,content:"Sabah koşusu + sağlıklı kahvaltı = Harika bir gün! ☀️",likes:203,comments:29,shares:14,time:"1 hafta önce",tags:["#sağlık","#spor"],img:"linear-gradient(135deg,#40916c,#2d6a4f)"},');
a('];');
a('');
a('const HIGHLIGHTS=[');
a('  {id:1,label:"Girişim",icon:"🚀",color:["#e63946","#c1121f"]},');
a('  {id:2,label:"Zirve",icon:"🏆",color:["#1d3557","#457b9d"]},');
a('  {id:3,label:"Spor",icon:"💪",color:["#2d6a4f","#40916c"]},');
a('  {id:4,label:"Seyahat",icon:"✈️",color:["#e76f51","#f4a261"]},');
a('  {id:5,label:"Eğitim",icon:"📚",color:["#457b9d","#1d3557"]},');
a('];');
a('');
a('const TABS=[{key:0,label:"Gönderiler",icon:"⊞"},{key:1,label:"Medya",icon:"🖼️"},{key:2,label:"Beğendiklerim",icon:"❤️"},{key:3,label:"Kaydettiklerim",icon:"🔖"}];');
a('');
a('function Flag({w,h}:{w:number,h:number}){return(');
a('  '+d+'svg width={w} height={h} viewBox="0 0 900 600" xmlns="http://www.w3.org/2000/svg" style={{display:"block"}}'+s);
a('    '+d+'rect width="900" height="600" fill="#E30A17"/'+s);
a('    '+d+'circle cx="300" cy="300" r="200" fill="white"/'+s);
a('    '+d+'circle cx="360" cy="300" r="160" fill="#E30A17"/'+s);
a('    '+d+'g transform="translate(530,300) rotate(-12)"'+s+d+'polygon fill="white" points="0,-80 18.6,-57.2 59.5,-24.7 30.4,21.9 37.3,65.2 0,40 -37.3,65.2 -30.4,21.9 -59.5,-24.7 -18.6,-57.2"/'+s+d+'/g'+s);
a('  '+d+'/svg'+s);
a(');}');
a('');
a('function Verified(){return('+d+'span style={{width:16,height:16,background:"#e63946",borderRadius:"50%",display:"inline-flex",alignItems:"center",justifyContent:"center",flexShrink:0}}'+s+d+'svg width="8" height="8" fill="white" viewBox="0 0 24 24"'+s+d+'path d="M20 6 9 17l-5-5"/'+s+d+'/svg'+s+d+'/span'+s+');}');
a('');

fs.writeFileSync('c:/Users/agity/Desktop/akgencler.com.tr/fix_profil_data.json',JSON.stringify(L),'utf8');
console.log('part1 ok',L.length);
