const fs = require('fs');
const p = 'c:/Users/agity/Desktop/akgencler.com.tr/src/app/profil/[id]/page.tsx';

let c = '';
c += '"use client";\n';
c += 'import React, { useState, useRef } from "react";\n';
c += 'import { useParams } from "next/navigation";\n';
c += 'import PageLayout from "@/components/PageLayout";\n';
c += 'import { useStore } from "@/store/useStore";\n';
c += 'import FollowersModal from "@/components/FollowersModal";\n';
c += 'import { showToast } from "@/components/Toast";\n';
c += 'import Avatar from "@/components/Avatar";\n';
c += 'import PostCard from "@/components/PostCard";\n\n';
c += 'const TABS = ["G\u00f6nderiler", "Be\u011feniler", "Kaydettiklerim", "Etiketlenenler"];\n\n';
c += 'export default function ProfilPage() {\n';
c += '  const { id } = useParams<{ id: string }>();\n';
c += '  const { users, currentUser, posts, followUser, unfollowUser, updateProfile, stories } = useStore();\n';
c += '  const [tab, setTab] = useState(0);\n';
c += '  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");\n';
c += '  const [editOpen, setEditOpen] = useState(false);\n';
c += '  const [editName, setEditName] = useState("");\n';
c += '  const [editUsername, setEditUsername] = useState("");\n';
c += '  const [editBio, setEditBio] = useState("");\n';
c += '  const [editLoc, setEditLoc] = useState("");\n';
c += '  const [editWeb, setEditWeb] = useState("");\n';
c += '  const [editGender, setEditGender] = useState("");\n';
c += '  const [editBirth, setEditBirth] = useState("");\n';
c += '  const [followModal, setFollowModal] = useState<"followers" | "following" | null>(null);\n';
c += '  const [coverPhoto, setCoverPhoto] = useState<string | null>(null);\n';
c += '  const [profilePhoto, setProfilePhoto] = useState<string | null>(null);\n';
c += '  const [shareOpen, setShareOpen] = useState(false);\n';
c += '  const coverInputRef = useRef<HTMLInputElement>(null);\n';
c += '  const avatarInputRef = useRef<HTMLInputElement>(null);\n\n';
c += '  const profileId = id === "me" ? "me" : id;\n';
c += '  const isMe = profileId === "me" || profileId === currentUser.id;\n';
c += '  const user = isMe ? currentUser : users.find((u) => u.id === profileId);\n\n';
c += '  if (!user) return (\n';
c += '    <PageLayout>\n';
c += '      <div style={{ background: "#fff", borderRadius: 18, padding: "48px 24px", textAlign: "center" }}>\n';
c += '        <p style={{ fontSize: 36, margin: "0 0 12px" }}>\uD83D\uDD0D</p>\n';
c += '        <p style={{ fontWeight: 700, color: "#374151" }}>Kullan\u0131c\u0131 bulunamad\u0131</p>\n';
c += '      </div>\n';
c += '    </PageLayout>\n';
c += '  );\n\n';
c += '  const isFollowing = currentUser.following.includes(user.id);\n';
c += '  const userPosts = posts.filter((p) => p.authorId === user.id);\n';
c += '  const likedPosts = posts.filter((p) => p.likes.includes(user.id));\n';
c += '  const savedPosts = posts.filter((p) => p.bookmarks.includes(user.id));\n';
c += '  const displayed = tab === 0 ? userPosts : tab === 1 ? likedPosts : tab === 2 ? savedPosts : [];\n';
c += '  const profileUrl = `https://akgencler.com.tr/profil/${user.id}`;\n\n';
c += '  function openEdit() {\n';
c += '    setEditName(currentUser.name); setEditUsername(currentUser.username);\n';
c += '    setEditBio(currentUser.bio); setEditLoc(currentUser.location); setEditWeb(currentUser.website);\n';
c += '    setEditOpen(true);\n  }\n\n';
c += '  function saveEdit() {\n';
c += '    updateProfile({ name: editName, bio: editBio, location: editLoc, website: editWeb });\n';
c += '    setEditOpen(false); showToast("Profil g\u00fcncellendi \u2705");\n  }\n\n';
c += '  function handleCoverChange(e: React.ChangeEvent<HTMLInputElement>) {\n';
c += '    const file = e.target.files?.[0]; if (!file) return;\n';
c += '    const reader = new FileReader();\n';
c += '    reader.onload = (ev) => { setCoverPhoto(ev.target?.result as string); showToast("Kapak foto\u011fraf\u0131 g\u00fcncellendi \u2705"); };\n';
c += '    reader.readAsDataURL(file);\n  }\n\n';
c += '  function handleAvatarChange(e: React.ChangeEvent<HTMLInputElement>) {\n';
c += '    const file = e.target.files?.[0]; if (!file) return;\n';
c += '    const reader = new FileReader();\n';
c += '    reader.onload = (ev) => { setProfilePhoto(ev.target?.result as string); showToast("Profil foto\u011fraf\u0131 g\u00fcncellendi \u2705"); };\n';
c += '    reader.readAsDataURL(file);\n  }\n\n';
c += '  function copyLink() { navigator.clipboard.writeText(profileUrl); showToast("Link kopyaland\u0131 \uD83D\uDD17"); setShareOpen(false); }\n\n';

fs.writeFileSync(p, c, 'utf8');
console.log('part1 written:', c.length);
